# name: ParticleGun.mac
# date: 3/20/2024
# author: Arthur Zangi
# email: szangi@mit.edu
#
#Particle Gun Sources generally have to be defined by the user
#through the command line interface, so we provide a macro here
#to initialize it once to some default values which can be changed
#from the command line later.
#
/run/initialize
#
/gps/verbose 0
#
# 1x1 cm square plane source
/gps/source/add 50.0
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0. 0. -49. cm
/gps/pos/halfx 0.1 cm
/gps/pos/halfy 0.1 cm
#
#we'll set the momentum direction for now instead of setting a
#specific angular distribution
#
/gps/direction 0. 0. +1.
#
# particle definition
/gps/particle gamma     
#
#Gaussian Energy Definition
#/gps/ene/type Gauss 
#/gps/ene/sigma 5. MeV
#/gps/ene/mono 1.5 MeV
#
# Linear Energy Definition for White Spectrum
#/gps/ene/type Lin
#/gps/ene/gradient 0
#/gps/ene/intercept 1
# set the energy range
#/gps/ene/min 1 MeV
#/gps/ene/max 4 MeV

## set the energy definition
/gps/ene/mono 2 MeV
#
# set up a second identical source but of gammas instead
/gps/source/add 50.0
/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0. 0. -49. cm
/gps/pos/halfx 0.1 cm
/gps/pos/halfy 0.1 cm
/gps/direction 0. 0. +1.
/gps/ene/mono 2.0 MeV

/analysis/openFile ScintTests.root
/RMatrix/output/setDataOutput on
/RMatrix/output/setFileName ScintTests.csv
/run/beamOn 100
/analysis/write
/analysis/closeFile
#