# name: ParticleGun.mac
# date: 3/20/2024
# author: Arthur Zangi
# email: szangi@mit.edu
#
#Particle Gun Sources generally have to be defined by the user
#through the command line interface, so we provide a macro here
#to initialize it once to some default values which can be changed
#from the command line later.
#
/run/initialize
#
/gps/verbose 0
#
# Cylindrical particle source matching the shape of the detector
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. -10. cm
/gps/pos/radius 2.54 cm
/gps/pos/halfz 2.5 cm
#/gps/position 1.0 0.0 -8.0 cm
/gps/ang/type iso

#
# leave the angular distribution isotropic
#
#
# particle definition
/gps/particle opticalphoton     
#
#

## set the energy definition
/gps/ene/mono 2.36 eV
#
/RMatrix/output/setDataOutput on
/RMatrix/output/setFileName EJ301_OpticalPhotonTransport.csv
/run/beamOn 50

/vis/open TSG
/vis/plot h2 0
#